import os
from pathlib import Path
from dotenv import load_dotenv
from src.utils.llm_client import generate
from src.security.guardrails import sanitize_output
from src.prompts.prompts import MEMO_PROMPT_TEMPLATE

load_dotenv()

REPORT_SYSTEM = (
    "You are an expert scientific report writer. "
    "Write a clear, confident, professional memo for a research manager. "
    "Be specific. Keep it under 250 words. Never make up data."
)


def run_report_agent(context: dict, prioritization: dict) -> str:
    ranked = prioritization["ranked"]
    explanation = prioritization["ranking_explanation"]
    constraints = context["constraints"]

    ranked_summary = ""
    for i, row in ranked.iterrows():
        ranked_summary += (
            f"{i+1}. {row['experiment_id']} — {row['control_parameter']} field\n"
            f"   Alignment={row['alignment_score']}, Stability={row['stability_score']}, "
            f"Cost={row['cost_estimate_eur']} EUR, Score={row['composite_score']}\n"
            f"   Notes: {row['notes_summary']}\n\n"
        )

    full_prompt = f"""
Project objective: {constraints['business_objective']}
Scientific objective: {constraints['scientific_objective']}

Experiment ranking and explanation:
{explanation}

Top {len(ranked)} ranked experiments:
{ranked_summary}

{MEMO_PROMPT_TEMPLATE}
"""

    memo = sanitize_output(generate(REPORT_SYSTEM, full_prompt))

    Path("output").mkdir(exist_ok=True)
    with open("output/sample_report.md", "w") as f:
        f.write("# R&D Experiment Prioritization — Decision Memo\n\n")
        f.write(memo)
        f.write("\n\n---\n_Generated by R&D Experiment Prioritization Agent_\n")

    ranked.to_json("output/sample_ranked_experiments.json", orient="records", indent=2)
    return memo
